name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # NEW STEP: Set version and commit hash
      - name: Set image tag variables
        id: vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(cat version.txt || echo 'v0.0.1')" >> $GITHUB_ENV

      # UPDATED STEP: Push multiple tags
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            queenie324/medic_care:latest
            queenie324/medic_care:${{ env.VERSION }}
            queenie324/medic_care:${{ env.SHORT_SHA }}

