# GitHub Actions workflow to build and push a Docker image to Docker Hub

name: Build and Push Docker Image

# Trigger this workflow on push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (enhanced Docker builder with caching, multi-platform support, etc.)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using secrets stored in GitHub
      # Secrets are defined in repo settings under: Settings > Secrets > Actions
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # Docker Hub access token

      # Step 4: Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .                      # Build context (current directory)
          push: true                      # Push the image to Docker Hub
          tags: queenie324/medic_care:latest  # Docker Hub repo/image:tag
